BM2\SiteBundle\Entity\User:
   constraints:
      - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
   properties:
      email:
         - Email: ~

# doesn't work - is enforced on road construction, but not on feature construction
#BM2\SiteBundle\Entity\GeoFeature:
#   properties:
#      name:
#         - NotBlank: ~
#         - Length:
#            min: 3

BM2\SiteBundle\Entity\SettlementPermission:
   properties:
      value:
         - LessThan:
            value: 10000000
